### PR TITLE
Creates Docker image for the build and run environment.

### PR DESCRIPTION
**Pull request by BillWSY**

### CODE REVIEW

**Comment by BillWSY** [comment]
Ruffin, can you test the docker image by checkouting the ```echo branch``` at ```~/workspace```, and do ```bazel run cogrob/speech/echo_agent:echo_agent```?

Also, can you PTAL and determine what is the best practice of using Docker in this system.

Docker seems not supporting sandboxing, which will prevent Bazel to fail when the dependency is not correctly written in BUILD files. Is there anything we can do about it? Or we should just live with it -- after all we are not using Docker in our development environment.

**Comment by BillWSY** [comment]
FYI, https://bazel.io/blog/2015/09/11/sandboxing.html

**Comment by ruffsl** [comment]
I've cleaned the dockerfile and added what I've found that Google is using, but bazel is still complain about after its told not to. :/
https://github.com/tensorflow/tensorflow/blob/1dba78b997dc49df9df663a838e0bacd6602f5b8/tensorflow/tools/docker/Dockerfile.devel-gpu#L61-L69

**Comment by BillWSY** [comment]
LGTM (based on trusting Ruffin is a Docker expert). Please merge to master.

**Pull request merged**
